# Generated by Django 4.0.7 on 2024-04-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(null=True, upload_to='bannerlogo/')),
                ('destext', models.TextField(blank=True, null=True)),
                ('websites', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField()),
                ('footer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(null=True, upload_to='bannerlogo/')),
                ('productname', models.CharField(blank=True, max_length=255, null=True)),
                ('productdesc', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('prict', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template1_product', to='management.template1')),
            ],
        ),
    ]
