# Generated by Django 4.0.7 on 2024-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template1',
            old_name='destext',
            new_name='abouttext',
        ),
        migrations.RenameField(
            model_name='template1',
            old_name='footer',
            new_name='productitle',
        ),
        migrations.RemoveField(
            model_name='template1',
            name='info',
        ),
        migrations.AddField(
            model_name='template1',
            name='moreinfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template1',
            name='templatename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
