# Generated by Django 4.0.7 on 2024-04-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_prict_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template1',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='template1',
            name='productitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
