# Generated by Django 4.0.7 on 2024-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_template1_status_alter_template1_productitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template1',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
