# Generated by Django 4.0.7 on 2024-04-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_template1_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(null=True, upload_to='template2/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deartext', models.TextField(blank=True, null=True)),
                ('abouttext', models.TextField(blank=True, null=True)),
                ('exploretext', models.TextField(blank=True, null=True)),
                ('dontmisstext', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(null=True, upload_to='template1_product/'),
        ),
        migrations.AlterField(
            model_name='template1',
            name='banner',
            field=models.ImageField(null=True, upload_to='template1/'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template1_list', to='management.template2')),
            ],
        ),
    ]
