# Generated by Django 4.0.7 on 2024-04-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_template2_alter_product_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listtemplate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template2_list', to='management.template2')),
            ],
        ),
        migrations.CreateModel(
            name='Listtemplate4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='paragraphtemplate5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parapgrah', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(null=True, upload_to='template3/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deartext', models.TextField(blank=True, null=True)),
                ('abouttext', models.TextField(blank=True, null=True)),
                ('eventheading', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('dontmiss', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(null=True, upload_to='template4/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deartext', models.TextField(blank=True, null=True)),
                ('abouttext', models.TextField(blank=True, null=True)),
                ('dontmisstext', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('moreinfo', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(null=True, upload_to='template5/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deartext', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='paragraphtemplate5',
            name='template5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template4_paragraph', to='management.template5'),
        ),
        migrations.AddField(
            model_name='listtemplate4',
            name='template4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template4_list', to='management.template4'),
        ),
    ]
