# Generated by Django 4.0.7 on 2024-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_listtemplate2_listtemplate4_paragraphtemplate5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listtemplate2',
            old_name='template1',
            new_name='template2',
        ),
    ]
