# Generated by Django 4.0.7 on 2024-04-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_template1_listtemplate2_template2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paragraphtemplate5',
            new_name='paragraphtemplate4',
        ),
        migrations.RemoveField(
            model_name='listtemplate4',
            name='template4',
        ),
        migrations.DeleteModel(
            name='Template5',
        ),
        migrations.RenameField(
            model_name='template4',
            old_name='abouttext',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='template4',
            old_name='link',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='template4',
            old_name='moreinfo',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='paragraphtemplate4',
            name='template5',
        ),
        migrations.RemoveField(
            model_name='template4',
            name='dontmisstext',
        ),
        migrations.AddField(
            model_name='paragraphtemplate4',
            name='template4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template4_paragraph', to='management.template4'),
        ),
        migrations.AddField(
            model_name='template4',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template4',
            name='banner',
            field=models.ImageField(null=True, upload_to='template5/'),
        ),
        migrations.DeleteModel(
            name='Listtemplate4',
        ),
    ]
