# Generated by Django 4.0.7 on 2024-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2080-04-01'),
        ),
    ]
