# Generated by Django 4.0.7 on 2024-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0005_alter_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyname',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
