# Generated by Django 4.0.7 on 2024-04-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0006_user_companyname_user_logo_user_reg_user_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagescontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='messagecontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_content_instances', to='swiftauth.messagescontent'),
        ),
    ]
