# Generated by Django 4.0.7 on 2024-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0007_messagescontent_emaillog_messagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
