# Generated by Django 4.0.7 on 2024-04-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0009_user_webiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='webiste',
            new_name='website',
        ),
    ]
