# Generated by Django 4.0.7 on 2024-04-08 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0010_rename_webiste_user_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='email',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_message_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
