# Generated by Django 4.0.7 on 2024-04-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftauth', '0011_remove_emaillog_email_emaillog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='user',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
